@rem Set local directory if specified
@if "%GRADLE_OPTS%"=="" set GRADLE_OPTS=-Xmx64m -Xms64m"

@rem Set JAVA_HOME if not already set
@if "%JAVA_HOME%"=="" set JAVA_HOME=%~dp0..\..\jdk8u212-b04\jre

@rem Set JAVA_EXE if not already set
@if "%JAVA_EXE%"=="" set JAVA_EXE=%JAVA_HOME%\bin\java.exe

@rem Set CLASSPATH
@set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar

@rem Gradle start up script for Windows generated by Gradle.
@rem
@rem Important for running:
@rem (1) You need a JDK-8+ to run Gradle. To check, run 'java -version' and 'javac -version' to confirm.
@rem (2) You may need to set JAVA_HOME to the JDK installation directory.

@rem This command should be executed from the root project directory
@cd /D %~dp0

@rem Execute the Java command
%JAVA_EXE% %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%~n0" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
